# Generated by Django 4.2.11 on 2025-05-06 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Thread',
        ),
        migrations.RenameModel(
            old_name='PostCategory',
            new_name='ThreadCategory',
        ),
    ]
