# Generated by Django 5.2 on 2025-05-12 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0004_alter_job_manpower_required'),
        ('user_management', '0002_alter_profile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commission',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commissions_author', to='user_management.profile'),
        ),
    ]
