# Generated by Django 5.1.6 on 2025-05-11 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='header_image',
            field=models.ImageField(upload_to='media/blog/images/'),
        ),
    ]
