# Generated by Django 5.1.6 on 2025-03-10 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_article_options_alter_articlecategory_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='articlecategory',
            table='Article Categories',
        ),
    ]
