# Generated by Django 5.1.6 on 2025-03-10 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_articlecategory_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlecategory',
            options={'ordering': ['name'], 'verbose_name_plural': 'Article categories'},
        ),
        migrations.AlterModelTable(
            name='articlecategory',
            table=None,
        ),
    ]
